### ISSUE TITLE
Behavior of "file_event_stream = true" 

### ISSUE THREAD

**Issue by elelement** [civitaspo/fluent-plugin-cat-sweep#12]
I'm using the plugin to cat entire files to a kafka output, but what I'm seeing is that it is not sending an unique message with the whole file content. Instead, I'm receiving multiple small messages of 262 characters.

This is what my source looks like:
```xml
<source>
  @type cat_sweep
  file_path_with_glob /home/sources/dcm/*
  waiting_seconds 5
  tag pre.dcm
  format tsv
  keys Date,AdvertiserID,CampaignID,SiteID,PlacementID,AdID,CreativeID,ActivityGroupID,Act$
  remove_after_processing true
  file_event_stream true
</source>
```
Is this the expected behavior for a cat plugin? Shouldn't it be a unique message with the whole file content?

Thanks for your time.

**Comment by civitaspo** [comment]
Actually, the behaviour of this plugin is not what you are talking about.
`file_event_stream` option means gathering a whole file as *an event*, not *a message*.

See here => https://github.com/civitaspo/fluent-plugin-cat-sweep/blob/fff439e87a385744e99100322913c8408cd9e094/lib/fluent/plugin/in_cat_sweep.rb#L248-L260

This plugin finally uses `ArrayEventStream` when the option is specified. And, the `entries` are each lines of files (and time the line read). By using this, the times of `emit` is reduced, so the performance increases (though memory usage increases).

Does it make sence?

**Comment by elelement** [comment]
Yes it does!  :+1: . 

I'll try to figure out how to implement what I described to you. 

Thank you for your time!
